server:
  port: 8080

spring:

  config:
    import:
      - optional:file:deployments.yaml
      - classpath:deployments.yaml

  application:
    name: ${APPLICATION_NAME:subatomics-deploy}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  sql:
    init:
      mode: never
  main:
    banner-mode: off

management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  endpoints:
    web:
      exposure:
        include: health,info

app:
  gitlab:
    url: http://192.168.207.128:80
    token: glpat-7DRy8QmdXzPjxVcPAm_-
    project-id: 4
    branch: main