server:
  port: 8080

spring:

  config:
    import:
      - optional:file:deployments.yaml
      - classpath:deployments.yaml

  application:
    name: ${APPLICATION_NAME:subatomics-deploy}

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  sql:
    init:
      mode: never

springdoc:
  show-actuator: true

management:
  endpoints:
    web:
      base-path: "/infra"
      exposure:
        include: health, info, metrics, prometheus
        exclude: env
  prometheus:
    metrics:
      export:
        enabled: true

gitlab:
  url: http://gitlab.local:80
  token: glpat-7DRy8QmdXzPjxVcPAm_-

otel:
  exporter:
    otlp:
      endpoint: http://192.168.207.128:4318

  resource:
    attributes:
      k8s.cluster.name: "main-cluster"
      deployment.environment: "development"
      k8s.pod.ip: "127.0.0.1"
      k8s.namespace.name: "local"
      k8s.node.name: "localhost"
